services:
  postgres:
    image: postgres:15
    container_name: uhg_postgres
    environment:
      POSTGRES_USER: uhg_user
      POSTGRES_PASSWORD: uhg_pass
      POSTGRES_DB: uhg_claims
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U uhg_user -d uhg_claims"]
      interval: 10s
      timeout: 5s
      retries: 5

  mlflow:
    image: ghcr.io/mlflow/mlflow:v2.13.2
    container_name: uhg_mlflow
    ports:
      - "5000:5000"
    command: >
      mlflow server
      --host 0.0.0.0
      --port 5000
      --backend-store-uri sqlite:///mlflow.db
      --default-artifact-root /mlflow/artifacts
    volumes:
      - mlflow_data:/mlflow

  airflow:
    image: apache/airflow:2.9.1
    container_name: uhg_airflow
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://uhg_user:uhg_pass@postgres:5432/uhg_claims
      AIRFLOW__CORE__FERNET_KEY: "46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLt0nfdstY="
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      AIRFLOW__WEBSERVER__SECRET_KEY: "uhg-rag-secret"
      AIRFLOW__WEBSERVER__EXPOSE_CONFIG: "true"
      PINECONE_API_KEY: "${PINECONE_API_KEY}"
      GROQ_API_KEY: "${GROQ_API_KEY}"
      MLFLOW_TRACKING_URI: "http://mlflow:5000"
      DATABASE_URL: "postgresql://uhg_user:uhg_pass@postgres:5432/uhg_claims"
      PIPELINE_ROOT: "/opt/airflow"
    volumes:
      - ./dags:/opt/airflow/dags
      - ./ingestion:/opt/airflow/ingestion
      - ./retrieval:/opt/airflow/retrieval
      - ./data:/opt/airflow/data
      - ./requirements.txt:/opt/airflow/requirements.txt
    ports:
      - "8080:8080"
    command: >
      bash -c "
        pip install -r /opt/airflow/requirements.txt --quiet &&
        airflow db migrate &&
        airflow users create
          --username admin
          --password admin
          --firstname UHG
          --lastname Admin
          --role Admin
          --email admin@uhg.com || true &&
        airflow webserver &
        airflow scheduler
      "

volumes:
  pgdata:
  mlflow_data:
