apiVersion: v1
kind: Service
metadata:
  name: uhg-rag-api
  namespace: uhg-ai
  labels:
    app: uhg-rag-api
spec:
  selector:
    app: uhg-rag-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: ClusterIP
